name: CI
on: [push, pull_request]

jobs:
  core_test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
      - name: Install quartus-prime-lite
        run: nix profile install --impure "nixpkgs#quartus-prime-lite"
      - name: Test core
        run: make test
        working-directory: core

